// code: what Word writes in w:lang. lt: LanguageTool's code, null = no proofing.
export const LANGS = [
  { code: 'sv-SE', name: 'Svenska', en: 'Swedish', lt: 'sv-SE' },
  { code: 'en-GB', name: 'English (UK)', en: 'English, British', lt: 'en-GB' },
  { code: 'en-US', name: 'English (US)', en: 'English, American', lt: 'en-US' },
  { code: 'nb-NO', name: 'Norsk bokmål', en: 'Norwegian Bokmål', lt: 'nb' },
  { code: 'nn-NO', name: 'Norsk nynorsk', en: 'Norwegian Nynorsk', lt: null },
  { code: 'da-DK', name: 'Dansk', en: 'Danish', lt: 'da-DK' },
  { code: 'fi-FI', name: 'Suomi', en: 'Finnish', lt: null },
  { code: 'is-IS', name: 'Íslenska', en: 'Icelandic', lt: null },
  { code: 'de-DE', name: 'Deutsch', en: 'German', lt: 'de-DE' },
  { code: 'de-AT', name: 'Deutsch (Österreich)', en: 'German, Austria', lt: 'de-AT' },
  { code: 'de-CH', name: 'Deutsch (Schweiz)', en: 'German, Switzerland', lt: 'de-CH' },
  { code: 'fr-FR', name: 'Français', en: 'French', lt: 'fr-FR' },
  { code: 'fr-BE', name: 'Français (Belgique)', en: 'French, Belgium', lt: 'fr-BE' },
  { code: 'fr-CA', name: 'Français (Canada)', en: 'French, Canada', lt: 'fr-CA' },
  { code: 'es-ES', name: 'Español', en: 'Spanish', lt: 'es-ES' },
  { code: 'it-IT', name: 'Italiano', en: 'Italian', lt: 'it-IT' },
  { code: 'nl-NL', name: 'Nederlands', en: 'Dutch', lt: 'nl-NL' },
  { code: 'nl-BE', name: 'Nederlands (België)', en: 'Dutch, Belgium', lt: 'nl-BE' },
  { code: 'pt-PT', name: 'Português', en: 'Portuguese', lt: 'pt-PT' },
  { code: 'pt-BR', name: 'Português (Brasil)', en: 'Portuguese, Brazil', lt: 'pt-BR' },
  { code: 'pl-PL', name: 'Polski', en: 'Polish', lt: 'pl-PL' },
  { code: 'cs-CZ', name: 'Čeština', en: 'Czech', lt: null },
  { code: 'sk-SK', name: 'Slovenčina', en: 'Slovak', lt: 'sk-SK' },
  { code: 'sl-SI', name: 'Slovenščina', en: 'Slovenian', lt: 'sl-SI' },
  { code: 'hr-HR', name: 'Hrvatski', en: 'Croatian', lt: null },
  { code: 'hu-HU', name: 'Magyar', en: 'Hungarian', lt: null },
  { code: 'ro-RO', name: 'Română', en: 'Romanian', lt: 'ro-RO' },
  { code: 'el-GR', name: 'Ελληνικά', en: 'Greek', lt: 'el-GR' },
  { code: 'et-EE', name: 'Eesti', en: 'Estonian', lt: null },
  { code: 'lv-LV', name: 'Latviešu', en: 'Latvian', lt: null },
  { code: 'lt-LT', name: 'Lietuvių', en: 'Lithuanian', lt: null },
  { code: 'ru-RU', name: 'Русский', en: 'Russian', lt: 'ru-RU' },
  { code: 'uk-UA', name: 'Українська', en: 'Ukrainian', lt: 'uk-UA' },
  { code: 'ca-ES', name: 'Català', en: 'Catalan', lt: 'ca-ES' },
  { code: 'gl-ES', name: 'Galego', en: 'Galician', lt: 'gl-ES' },
  { code: 'ga-IE', name: 'Gaeilge', en: 'Irish', lt: 'ga-IE' },
  { code: 'tr-TR', name: 'Türkçe', en: 'Turkish', lt: null },
  { code: 'zh-CN', name: '中文（简体）', en: 'Chinese, Simplified', lt: 'zh-CN' },
  { code: 'ja-JP', name: '日本語', en: 'Japanese', lt: 'ja-JP' },
];

export const langByCode = code => LANGS.find(l => l.code === code)
  ?? { code, name: code, en: code, lt: null };
